/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCell: typeof import('./src/components/ArticleCell.vue')['default']
    ArticleContent: typeof import('./src/components/ArticleContent.vue')['default']
    FilterDrawer: typeof import('./src/components/FilterDrawer.vue')['default']
    MetaTree: typeof import('./src/components/MetaTree.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwipeCell: typeof import('./src/components/SwipeCell.vue')['default']
    TagManager: typeof import('./src/components/TagManager.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarPullRefresh: typeof import('@varlet/ui')['_PullRefreshComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarStep: typeof import('@varlet/ui')['_StepComponent']
    VarSteps: typeof import('@varlet/ui')['_StepsComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
}
