/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCell: typeof import('./src/components/ArticleCell.vue')['default']
    ArticleContent: typeof import('./src/components/ArticleContent.vue')['default']
    FilterDrawer: typeof import('./src/components/FilterDrawer.vue')['default']
    MetaTree: typeof import('./src/components/MetaTree.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwipeCell: typeof import('./src/components/SwipeCell.vue')['default']
    TagManager: typeof import('./src/components/TagManager.vue')['default']
  }
}
