"""Add proxy settings

Revision ID: 4ef7cf61fa7e
Revises: 113f7e9b92c9
Create Date: 2026-07-08 23:32:02.866382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef7cf61fa7e'
down_revision: Union[str, Sequence[str], None] = '113f7e9b92c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('proxy_enabled', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('proxy_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'proxy_url')
    op.drop_column('settings', 'proxy_enabled')
    # ### end Alembic commands ###
