"""add read_time to article_state

Revision ID: 73b15fbe4d3f
Revises: c9b6c5eb5a58
Create Date: 2026-07-18 12:53:43.840580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b15fbe4d3f'
down_revision: Union[str, Sequence[str], None] = 'c9b6c5eb5a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_state', sa.Column('read_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_state', 'read_time')
    # ### end Alembic commands ###
